MODEL:
  ARCHITECTURE: "MMN"
  MMN:
    NUM_CLIPS: 16
    JOINT_SPACE_SIZE: 256
    FEAT_TYPE: "VGG"  ## VGG or C3D
    FEATPOOL:
      INPUT_SIZE: 4096
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      #NAME: "conv"
      POOLING_COUNTS: [15] ## N-1
    TEXT_ENCODER:
      NAME: "BERT"
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 3 ## top_k for each gt
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.4
      CONTRASTIVE_WEIGHT: 0.05
DATASETS:
  NAME: "charades_combined"
  #TRAIN: ("charades_combined_train", )
  #TEST: ("charades_combined_test",)
  TRAIN: ("charades_separate_train_1gt", )
  TEST: ("charades_separate_test_1gt",)
  

INPUT:
  NUM_PRE_CLIPS: 32
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 24
  MILESTONES: (8, 13)
  MAX_EPOCH: 7
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 7
  #FREEZE_BERT: 4
  FREEZE_BERT: 0
  ONLY_IOU: 0
  SKIP_TEST: 0
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 48
  CONTRASTIVE_SCORE_POW: 0.5
